version: '3'

services:
    nginx:
        image: nginx:1.0.0
        container_name: nginx
        build:
            context: .
            dockerfile: Dockerfile-nginx
        networks:
            - my-net
        volumes:
            - ./nginx/conf/conf.d:/etc/nginx/conf.d
            - ./nginx/ssl:/etc/nginx/ssl
        ports:
            - '80:80'
            - '443:443'
        restart: on-failure
    app:
        container_name: app
        image: frontend:1.0.0
        build:
            context: .
            dockerfile: Dockerfile-app
        networks:
            - my-net
        volumes:
            - ./.env:/usr/src/app/.env
        ports:
            - '3000:3000'
        restart: on-failure
networks:
    instorage-net:
        driver: bridge
